import { ChevronLeft, MessageCircle, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useCart } from '../hooks/useCart'
import { orderInquiryUrl } from '../utils/whatsapp'

export function Cart() {
  const { items, total, increaseQuantity, decreaseQuantity, removeItem, clearCart } = useCart()
  return <div className="page cart-page"><div className="container"><Link className="back-link" to="/tienda"><ChevronLeft size={17}/> Seguir explorando</Link><div className="cart-heading"><div><p className="kicker">Tu selección</p><h1>Carrito de <em>consultas</em></h1></div>{items.length > 0 && <button className="clear-button" onClick={clearCart}><Trash2 size={16}/> Vaciar carrito</button>}</div>{items.length === 0 ? <div className="empty-state cart-empty"><span><ShoppingBag/></span><h2>Tu carrito está vacío</h2><p>Aún hay muchos detalles bonitos por descubrir.</p><Link className="button primary" to="/tienda">Explorar productos</Link></div> : <div className="cart-layout"><div className="cart-items">{items.map(({ product, quantity }) => <article className="cart-item" key={product.id}><img src={product.images[0]} alt={product.name}/><div className="cart-item-info"><small>Producto personalizado</small><Link to={`/producto/${product.slug}`}><h3>{product.name}</h3></Link><strong>{product.price ? `S/ ${product.price.toFixed(2)}` : 'Consultar'}</strong><div className="quantity"><button onClick={() => decreaseQuantity(product.id)}><Minus/></button><span>{quantity}</span><button onClick={() => increaseQuantity(product.id)}><Plus/></button></div></div><div className="cart-item-side"><button onClick={() => removeItem(product.id)} aria-label="Quitar producto"><Trash2/></button><strong>S/ {((product.price ?? 0) * quantity).toFixed(2)}</strong></div></article>)}</div><aside className="cart-summary"><p className="kicker">Resumen</p><h2>Tu consulta</h2><div><span>Productos</span><span>{items.reduce((s, i) => s + i.quantity, 0)}</span></div><div className="summary-total"><span>Total referencial</span><strong>S/ {total.toFixed(2)}</strong></div><p>El precio final se confirmará según personalización y disponibilidad.</p><a className="button primary" href={orderInquiryUrl(items)} target="_blank"><MessageCircle size={19}/> Consultar por WhatsApp</a><small>No se realizará ningún cobro en esta web.</small></aside></div>}</div></div>
}
