import { ArrowRight, AtSign, Clock, Heart, MapPin, MessageCircle, Phone, Send, Sparkles } from 'lucide-react'
import { type FormEvent, useState } from 'react'
import { Link } from 'react-router-dom'
import { INSTAGRAM_URL, PHONE_DISPLAY, TIKTOK_URL } from '../config'
import { ProductCard } from '../components/ProductCard'
import { TikTokCarousel } from '../components/TikTokCarousel'
import { products } from '../data/products'
import { whatsappUrl } from '../utils/whatsapp'

const categories = [
  { slug: 'quinceaneros', title: 'Quinceañeros', text: 'Detalles especiales para celebrar una fecha inolvidable.', image: products[0].images[0], number: '01' },
  { slug: 'matrimonios', title: 'Matrimonios', text: 'Recuerdos delicados para el comienzo de una gran historia.', image: products[3].images[0], number: '02' },
  { slug: 'bautizos', title: 'Bautizos', text: 'Pequeños símbolos para un día lleno de luz y ternura.', image: products[6].images[0], number: '03' },
  { slug: 'promocion', title: 'Promoción escolar', text: 'Celebra los logros y amistades que quedarán para siempre.', image: products[9].images[0], number: '04' },
]

export function Home() {
  const [form, setForm] = useState({ name: '', phone: '', message: '' })
  const submit = (event: FormEvent) => { event.preventDefault(); window.open(whatsappUrl(`Hola, soy ${form.name}. Mi teléfono es ${form.phone}.\n\n${form.message}`), '_blank') }
  return <>
    <section className="hero-section"><div className="container hero-grid"><div className="hero-copy"><p className="kicker"><Sparkles size={16}/> Diseñado para celebrar</p><h1>Detalles que hacen <em>inolvidables</em> tus momentos</h1><p>Recuerdos, decoración y productos personalizados creados con delicadeza para las celebraciones más importantes de tu vida.</p><div className="hero-actions"><Link className="button primary" to="/tienda">Ver colección <ArrowRight size={18}/></Link><a className="button ghost" href={whatsappUrl('Hola, quisiera información sobre sus productos.')} target="_blank"><MessageCircle size={18}/> Hablemos</a></div><div className="hero-note"><span>✦</span><p><strong>Hecho con cariño en Perú</strong><br/>Personalizamos cada detalle para ti</p></div></div><div className="hero-visual"><div className="hero-blob"></div><img src={products[3].images[0]} alt="Celebración elegante con detalles personalizados"/><div className="floating-card"><Heart size={20}/><span><strong>+500</strong> momentos celebrados</span></div><span className="hero-caption">Detalles que cuentan tu historia</span></div></div></section>
    <section className="section categories-section" id="categorias"><div className="container"><div className="section-heading centered"><p className="kicker">Encuentra tu celebración</p><h2>Cada momento merece <em>su propio detalle</em></h2><p>Explora nuestras colecciones pensadas para acompañarte en cada ocasión.</p></div><div className="category-grid">{categories.map((category) => <Link className="category-card" to={`/tienda?categoria=${category.slug}`} key={category.slug}><img src={category.image} alt={category.title} loading="lazy"/><div className="category-shade"></div><span className="category-number">{category.number}</span><div><h3>{category.title}</h3><p>{category.text}</p><span className="category-link">Ver productos <ArrowRight size={16}/></span></div></Link>)}</div></div></section>
    <section className="section products-section"><div className="container"><div className="section-heading split"><div><p className="kicker">Los más queridos</p><h2>Detalles para <em>enamorarte</em></h2></div><Link to="/tienda">Ver toda la colección <ArrowRight size={17}/></Link></div><div className="product-grid">{products.filter((p) => p.featured).slice(0, 4).map((p) => <ProductCard product={p} key={p.id}/>)}</div></div></section>
    <section className="section videos-section" id="videos"><div className="container"><div className="section-heading"><p className="kicker">Momentos reales</p><h2>Inspírate con <em>nuestros trabajos</em></h2><p>Un poquito de la magia que creamos todos los días.</p></div><TikTokCarousel/></div></section>
    <section className="section contact-section" id="contacto"><div className="container contact-shell"><div className="contact-copy"><p className="kicker">Estamos para ayudarte</p><h2>Hagamos realidad <em>tu idea</em></h2><p>Cuéntanos qué estás celebrando. Te acompañaremos para crear detalles tan únicos como tu historia.</p><div className="contact-list"><a href={whatsappUrl('Hola, quisiera hacer una consulta.')} target="_blank"><MessageCircle/><span><small>WhatsApp</small>{PHONE_DISPLAY}</span></a><a href={`tel:${PHONE_DISPLAY}`}><Phone/><span><small>Teléfono</small>{PHONE_DISPLAY}</span></a><a href={INSTAGRAM_URL} target="_blank"><AtSign/><span><small>Instagram</small>@celebrabonito.pe</span></a><span><Clock/><span><small>Horario</small>Lun–Sáb · 9:00 a 19:00</span></span><span><MapPin/><span><small>Atención</small>Lima, Perú · Envíos coordinados</span></span><a href={TIKTOK_URL} target="_blank">TikTok · @celebrabonito</a></div></div><form className="contact-form" onSubmit={submit}><span className="form-icon"><Send/></span><h3>Cuéntanos sobre tu evento</h3><p>Te responderemos directamente por WhatsApp.</p><label>Tu nombre<input required placeholder="¿Cómo te llamas?" value={form.name} onChange={(e) => setForm({...form, name: e.target.value})}/></label><label>Teléfono<input required type="tel" placeholder="+51 999 999 999" value={form.phone} onChange={(e) => setForm({...form, phone: e.target.value})}/></label><label>Mensaje<textarea required rows={4} placeholder="Cuéntanos qué estás buscando..." value={form.message} onChange={(e) => setForm({...form, message: e.target.value})}/></label><button className="button primary" type="submit">Enviar por WhatsApp <MessageCircle size={18}/></button></form></div></section>
  </>
}
